java racing car 손현경
JavaBlooming-In-Spring/java-challenges pull request #11
Opened 2022-07-29 14:03 UTC by shkisme

약 3시간 소요..
테스트 코드 너무 어려워요!!😥

2022-07-30 06:10 UTC, gusah009 reviewed
코드가 수정되면서 테스트도 수정 될 수 있을 것 같아서 테스트쪽은 아직 코드리뷰 안했습니다!

2022-07-30 06:10 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Game.java
> +  Game(User user, GameController gameController){
이전에 말씀드린 formatter 사용해보면 좋을 것 같습니다!

2022-07-30 06:10 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Game.java
> +        if (isNumberGreaterThanFour(generateRandomNumber())){
indent depth가 3을 넘은 것 같습니다.

2022-07-30 06:10 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Game.java
> +
메서드 내부는 빈 칸을 없애고 더 추상화 단계를 높일 수 있지 않을까요?

2022-07-30 06:10 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Game.java
> +    for (int i = 0; i< tryNumber; i++){
for문 내부에 하는 역할이 여러개 있는 것 같습니다. 아래 indent가 3을 넘어가는 문제를 해결하다 보면 역할을 분리할 수 있을 것 같습니다!

2022-07-30 06:10 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Game.java
> +  List<String> winnerList = new ArrayList<>();
각 필드들을 package-private으로 하신 이유가 있나요?

+ 각 필드들을 non-final로 하신 이유가 있나요?

2022-07-30 06:10 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Game.java
> +  private boolean isNumberGreaterThanFour(int randomNumber){
isXXX 메서드를 잘 사용하신 것 같습니다! 👍

2022-07-30 06:10 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Game.java
> +  private void printScore(){
String.repeat() 메서드를 이용해 2중 for문을 조금 더 간단하게 줄일 수 있을 것 같습니다!

2022-07-30 06:10 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/GameController.java
> +public class GameController {
이름에 Controller를 붙이신 이유가 있을까요?

2022-07-30 06:10 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/User.java
> +    private String carName;
carName보다 carNames가 더 어울리는 것 같습니다!

2022-07-30 06:10 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/User.java
> +    public void setCarName(){
`setCarName`말고 다른 메서드 명은 어떨까요? 

`initCarName`도 괜찮은 것 같습니다.

2022-07-30 06:10 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/User.java
> +    public void closeScanner(){
이 메서드를 non static으로 선언한 이유가 있나요? 여러 User를 생성하는 상황이 올 수도 있어서 정적인 자원을 객체가 해제하는 것은 위험할 것 같습니다.

2022-07-30 07:29 UTC, JeonghakLee requested changes

2022-07-30 07:29 UTC, JeonghakLee commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Game.java
> +    List<Integer> list = new ArrayList<>();
int max 값만 리턴하는 메서드라면 
max를 0으로 초기화 해두고 반복해서 car.getScore()의 값만 비교하여 최댓값을 구하는 방법도 있는데
List를 새로 생성하여 max를 구하는 방식을 선택하신  이유가 있을까요??

2022-07-30 07:29 UTC, JeonghakLee commented on shkisme/java_racing_car/src/test/java/java_racing_car/java_racing_car/CarTest.java
> +    Assertions.assertThat(gameController.list.contains("jun"));
Assertions.assertThat(gameController.list.contain("pobi", "woni", "jun));
이렇게 작성할 수 있을 것 같은데 하지 않으신 이유가 있으신가요??

2022-07-30 07:29 UTC, JeonghakLee commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/GameController.java
> +
그냥 list라는 이름은 어떤 리스트인지 의미가 불분명한 것 같습니다!

2022-07-30 07:35 UTC, JeonghakLee commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/GameController.java
> +        printTryNumberError();
시도 횟수가 0~9 사이의 값이라는 요구사항이 있었나요??

2022-07-30 13:03 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Game.java
> +  Game(User user, GameController gameController){
앗...! 단축키 세팅이 잘못되어있었네요 적용했습니다!

2022-07-30 13:12 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/GameController.java
> +public class GameController {
적당한 이름이 안떠올라서 Controller로 지었습니다! 더 좋은 이름이 있을까요..?

2022-07-30 13:24 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/User.java
> +    public void closeScanner(){
이부분은 전혀 생각을 못했네요.. 수정했습니다!!

2022-07-30 13:32 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Game.java
> +    List<Integer> list = new ArrayList<>();
Collections.max() 메서드를 사용해보고자 이 방식을 택했습니다
근데 다시보니 리스트를 생성하는 과정이 비효율적이군요..  수정했습니다!

2022-07-30 13:33 UTC, shkisme commented on shkisme/java_racing_car/src/test/java/java_racing_car/java_racing_car/CarTest.java
> +    Assertions.assertThat(gameController.list.contains("jun"));
위 처럼 작성 시 오류가 떠서 이렇게 작성했습니다!

2022-07-30 13:35 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/GameController.java
> +        printTryNumberError();
엇?? 랜덤 값이랑 착각을 했네요 수정했습니다!

2022-07-30 13:38 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/GameController.java
> +        printTryNumberError();
뭔가 요구사항을 잘못읽고 착각하였네요 수정했습니다!

2022-07-30 13:44 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/GameController.java
> +public class GameController {
음... 딱히 다른 이름을 생각하고 여쭤본 건 아니고, 웹 MVC 패턴의 `Controller`와 이름이 겹쳐서 비슷한 기능을 하는 줄 알았습니다!

지금 프로젝트는 웹과 아무 관련이 없어서 `Controller`도 괜찮은 것 같습니다.

2022-07-30 13:57 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Game.java
> +    for (int i = 0; i< tryNumber; i++){
수정하였습니다!!

2022-07-30 14:10 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Game.java
> +  List<String> winnerList = new ArrayList<>();
이유는 없고.. 빼먹은거같습니다😂 뭔가 private, final 선언을 적절하게 하기 어렵네요... 이부분을 더 공부해야겠습니다!

2022-07-31 01:04 UTC, woo-chang reviewed
다른 분들이 리뷰를 너무 잘해주셔서 저는 크게 할게 없었네요 수고하셨습니다 😎

2022-07-31 01:04 UTC, woo-chang commented on shkisme/java_racing_car/src/test/java/java_racing_car/java_racing_car/InputTest.java
>      Assertions.assertThat(user.getCarNameList().length).isEqualTo(3);
단순히 길이만 비교하기보다는 입력한 값에 대해서 정확한 리스트를 가지고 있는지 비교해 보는 것도 좋을 것 같습니다~

2022-07-31 01:04 UTC, woo-chang commented on shkisme/java_racing_car/src/test/java/java_racing_car/java_racing_car/WinnerTest.java
>      game.generateWinnerList(game.getHighestScore());
우승자 테스트도 마찬가지로 정확히 누가 우승했는지 비교해본다면 좋을 것 같아요!

2022-07-31 09:13 UTC, JeonghakLee commented on shkisme/java_racing_car/src/test/java/java_racing_car/java_racing_car/CarTest.java
> +    Assertions.assertThat(gameController.list.contains("jun"));
혹시 어떤 오류가 뜨는지 알 수 있을까요??

2022-07-31 11:48 UTC, shkisme commented on shkisme/java_racing_car/src/test/java/java_racing_car/java_racing_car/CarTest.java
> +    Assertions.assertThat(gameController.list.contains("jun"));
![java_racing_car – CarTest java  java_racing_car test  2022-07-31 오후 8_46_34](https://user-images.githubusercontent.com/92802207/182024830-77b6a9dd-70c0-42ab-aea9-1cc113bf3f59.png)

이렇게 됩니다!

2022-07-31 11:54 UTC, shkisme commented on shkisme/java_racing_car/src/test/java/java_racing_car/java_racing_car/WinnerTest.java
>      game.generateWinnerList(game.getHighestScore());
수정하였습니다!! 감사합니다👍

2022-07-31 12:27 UTC, gusah009 commented on shkisme/java_racing_car/src/test/java/java_racing_car/java_racing_car/CarTest.java
> +    Assertions.assertThat(gameController.list.contains("jun"));
살짝 오지랖좀 부려보자면 아래와 같이 하는 게 좋을 것 같습니다~

```java
Assertions.assertThat(gameController.list.containsAll(List.of("pobi", "woni", "jun")));
```

여기서 조금 더 오지랖을 부려보자면, `assertJ`의 테스팅에는 아래와 같이 왠만한 메서드를 다 지원해줍니다!
```java
Assertions.assertThat(gameController.list).containsAll(List.of("pobi", "woni", "jun"));
```

2022-07-31 12:35 UTC, shkisme commented on shkisme/java_racing_car/src/test/java/java_racing_car/java_racing_car/CarTest.java
> +    Assertions.assertThat(gameController.list.contains("jun"));
감솨합니다.. 자바 메서드 사용이 익숙치않네요 ㅜㅜ

2022-07-31 12:40 UTC, gusah009 reviewed
테스트 코드는 로직상 문제 없이 잘 짜셨네요!!

그런데 단위 테스트의 느낌 보다는 전부 통합 테스트의 느낌이 강합니다... 서로의 클래스가 서로에게 의존성을 강하게 가지고 있어서 그런 것 같아요.

조금 더 클래스끼리 역할과 책임을 생각하면서 분리하시면 지금처럼 항상 `System.in`으로 데이터를 넣지 않고, 단위 테스트를 하는 것이 가능할 것 같습니다!

2022-07-31 12:40 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Error.java
> +  NO_ERROR(false);
포맷팅 편안... **ㅇvㅇ**

2022-07-31 12:40 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Main.java
> +    Game game = new Game(user, gameController);
`Game`과  `GameController`의 차이는 뭔가요?

2022-07-31 12:40 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Main.java
> +
빈 칸으로 비우셨다는 뜻은 위의 코드와 아래 코드가 서로 다른 역할을 하고 있다고 판단하신 걸로 보입니다. 그렇다면 서로 다른 메서드나 혹은 **클래스**로 나누셔도 되지 않을까요?

> 개인적으로는 새로운 클래스가 생겼으면 좋겠습니다. `Main` 클래스가 하는 일이 너무 많아요.

2022-07-31 12:40 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/User.java
> +  public void initCarName() {
`initCarName()` 메서드가 꼭 필요할까요?

2022-07-31 12:40 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/User.java
> +  public void setTryNumber() {
`setTryNumber`보다는 위와 같이 `initTryNumber`가 좋아보이긴 합니다!

> 그런데 꼭 필요한 메서드인가요?

2022-07-31 13:42 UTC, JeonghakLee commented on shkisme/java_racing_car/src/test/java/java_racing_car/java_racing_car/CarTest.java
> +    Assertions.assertThat(gameController.list.contains("jun"));
Assertions.assertThat(gameController.list).contains("pobi", "woni", "jun); 이거 였는데 제가 코드 예시가 조금 잘못 되었었습니다..ㅎ 현모님이 잘 제시해주셨네요!

2022-08-01 02:16 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/User.java
> +  public void setTryNumber() {
에러가 뜰 때 마다 저장해둔 값을 초기화 시켜줘야 한다고 생각한 것 같습니다...
근데 없어도 정상적으로 돌아가네요😂 수정했습니다!

2022-08-01 02:25 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Main.java
> +    Game game = new Game(user, gameController);
Game은 자동차들의 랜덤 값으로 경주 게임을 하는 클래스이고, GameController는 전체를 관리하는 클래스입니다
Game 클래스 명을 좀 더 구체적으로 바꾸었습니다!

2022-08-01 07:59 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Main.java
> +
새로운 클래스를 만들고, 메서드를 수정했습니다! 그래도 여전히.. Main 클래스가 하는 일이 많아보이네요..ㅜㅜ
처음에 설계할 때 클래스의 역할을 좀 더 확실히 분리했어야 했던 것 같아요. 이 부분 배워갑니다😂👍

2022-08-02 07:31 UTC, JeonghakLee approved these changes

2022-08-02 07:35 UTC, gusah009 approved these changes

2022-08-02 07:35 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/RacingGame.java
> +  private void racingCar() {
포맷팅 좋습니다~!

2022-08-02 07:35 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Main.java
> +    gameController.generateList();
이건 어떤 `List`를 생성하고 있는걸까요?

2022-08-02 07:35 UTC, gusah009 commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/RacingGame.java
>    List<String> winnerList = new ArrayList<>();
`package-private`으로 푼 이유가 있을까요?

2022-08-02 07:37 UTC, woo-chang approved these changes
😊😊

2022-08-02 08:07 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/Main.java
> +    gameController.generateList();
generateCarNameList() 메서드와 generateCarList() 메서드를 함께 호출하는 generateList() 메서드입니다!
차 이름 리스트와 차 리스트 모두를 생성하고 있습니다..

2022-08-02 08:09 UTC, shkisme commented on shkisme/java_racing_car/src/main/java/java_racing_car/java_racing_car/RacingGame.java
>    List<String> winnerList = new ArrayList<>();
다른 값이 재할당 되는 것을 막기위해 private final로 선언하였습니다!

2022-08-02 08:30 UTC, merged