Java lotto 손현경
JavaBlooming-In-Spring/java-challenges pull request #15
Opened 2022-08-04 14:33 UTC by shkisme

소요시간 : 많이 소요...
뭔가 이상하게 업로드되어서 다시 업로드합니다!

2022-08-09 02:21 UTC, gusah009 requested changes
면접때문에 리뷰가 늦었습니다! 늦은만큼 열심히 리뷰했습니다~!!

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/ErrorMessage.java
> +public enum ErrorMessage {
`message`, `error` 각각 받는 것 보다, 클래스를 2개로 나누는 게 좋을 것 같습니다.

`message`를 할당받지 않은 `ERROR` 객체도 `ERROR.getMessage()`를 호출할 수 있고, `CANNOT_NEGATIVE.getError()`를 부를 수도 있기 때문에  서로 나누는 게 좋다고 생각합니다!

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/ErrorMessage.java
> +  LACK_MONNEY("구매할 돈이 부족합니다."),
오타!

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/Game.java
> +  private int bonusBall;
명명을 `bonusBall`보다 `lastWeekWinningBonusBall`로 위의 `lastWeekWinningLotto`와 맞춰주면 더 좋을 것 같습니다!

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/Game.java
> +      LottoGenerator lotto = new LottoGenerator(user);
1. `LottoGenerator`를 정적 팩터리 메서드로 만드는 건 어떨까요?
2. `LottoGenerator`의 이름에선 로또를 생성해서 반환하는 것 처럼 보이는데, 내부 구현을 살펴봤더니 로또를 생성하는 것 뿐만 아니라 **`user`에게 만들어진 로또를 대입시키는 로직도** 들어있는 것으로 확인됩니다. 두 가지 일을 하는 것 같은데, 클래스를 분리하거나 네이밍을 바꾸는 게 좋아보입니다!

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/Game.java
> +      lotto.lottoGeneratetor();
`Generatetor` 오타!

`LottoGenerator` 내부적으로 또 생성자가 아닌 `lottoGenerator` 메서드를 가지네요? 정적 팩터리 메서드로 만들어서 생성 할 때 아예 모든 일을 처리하도록 바꿀 수 있을 것 같습니다!

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +      winningLottoErrorCheck(extrackNumbers(winningLottoNumber));
`GameInput`에서 validation 체크까지 하는 것 같습니다. `Input`에서 모든 유효성 검사를 함께 진행하도록 설계하신건가요?

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/Game.java
> +  private void printRankList() {
혹시 `printRankList()` 메서드가 `GamePrint` 말고 `Game`클래스에 있는 이유가 있나요?

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/Game.java
> +  private void printTotalYield() {
혹시 `printTotalYield()` 메서드가 `GamePrint` 말고 `Game`클래스에 있는 이유가 있나요?

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +      e = new Exception(AMOUNT_OUT_OF_RANGE.getMessage());
해당 Exception이 amount의 범위를 벗어난 Exception이라고 장담할 수 있나요?

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +  private String[] extrackNumbers(String winningLottoNumber) {
`extrackNumbers` 오타!

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +    Lotto winningLotto = getWinningLotto(extrackNumbers(winningLottoNumber));
`stream`을 사용하면 `getWinningLotto()`와 `extrackNumbers()`를 하나로 합칠 수 있을 것 같습니다!

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +    Set<Integer> set = new HashSet<>();
`String`으로 바로 안넣고 `Integer`로 `parseInt`해서 넣는 이유가 있나요?

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +    List<ErrorMessage> error = new ArrayList<>();
오... error를 `List`로 담아서 확인하는 신기한 방법을 사용하셨는데, 그냥 Error 발생 시 `throw`하는 것 보다 장점이 있을까요?

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +  private ErrorMessage compareBallAndNumber(int number, int ball) {
`compareBallAndNumber` 명명으로는 왜 `Error`를 return하는 지 의미가 불분명한 것 같습니다. 또 두 값이 어떨 때 `ERROR`이고, 어떨 때 `NO_ERROR`인지 판단하기도 힘들 것 같은데 현경님은 어떻게 생각하시나요?

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/lotto/Lotto.java
> +  public List<Integer> getLotto() {
`WinningLotto`에서는 같은 이름의 `getLotto()`가 `Lotto` 클래스를 반환하는데 반해 여기 `getLotto()`메서드는 `List<Integer>`를 반환하는 것 같습니다. 명명을 확실하게 하거나, 같은 값을 반환하도록 하는 게 통일성이 있을 것 같습니다.

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/lotto/LottoGenerator.java
> +public class LottoGenerator {
`LottoGenerator` 클래스는 위의 리뷰처럼 의미가 불분명한 것 같아서 수정 뒤에 다시 살펴보겠습니다!

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/lotto/WinningLotto.java
> +  public Rank match(Lotto userLotto) {
굉장히 괜찮은 방법이긴 한데, 아래 요구사항항처럼 `RankRepository`를 이용해서 `Rank`를 받아오게 구현해보는 건 어떨까요?

<img width="437" alt="image" src="https://user-images.githubusercontent.com/26597702/183548976-2fc1f544-0e4d-498c-817d-bd4967ec06d3.png">

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/test/java/javalotto/javalotto/error/input/PurchasePriceTest.java
> +public class PurchasePriceTest {
테스트 코드들을 깔끔하게 짜신 것 같습니다 👍👍👍

2022-08-09 02:21 UTC, gusah009 commented on shkisme/java_lotto/src/test/java/javalotto/javalotto/error/input/PurchasePriceTest.java
> +public class PurchasePriceTest {
올바른 구입 금액일 때 성공 테스트도 있으면 좋을 것 같아요!

2022-08-09 08:49 UTC, shkisme commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +      winningLottoErrorCheck(extrackNumbers(winningLottoNumber));
GameInput에서 값을 받을 때 유효검사를 같이 하는 것도 괜찮을 것 같아서 이렇게 설계하였습니다! 클래스를 분리 하는 것이 좋을까요?

2022-08-09 12:26 UTC, shkisme commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +    List<ErrorMessage> error = new ArrayList<>();
indent depth가 2를 넘어가지 않도록 구현하다보니 이렇게 구현하게 되었어요😂

2022-08-09 13:08 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +      winningLottoErrorCheck(extrackNumbers(winningLottoNumber));
역할이란게 어느정도 주관적이고 너무 클래스가 많아지는것도 복잡해지니 원하시는대로 해도 좋을 것 같습니다!

현경님이 생각하실 때 유효성 검사 역할과 입력 역할이 구분된다고 생각하시면 분리하시는게 맞는 것 같고, 하나의 역할이라고 생각하시면 하나로 둬도 괜찮은 것 같습니다.

2022-08-09 13:15 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +    List<ErrorMessage> error = new ArrayList<>();
`stream`을 이용해 보는것도 좋을 것 같습니다!!

2022-08-09 13:15 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +    List<ErrorMessage> error = new ArrayList<>();
stream을 이용해 보는것도 좋을 것 같습니다!!

2022-08-09 15:07 UTC, shkisme commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/lotto/WinningLotto.java
> +  public Rank match(Lotto userLotto) {
RankRepository를 이용하는 것으로 수정했습니다! 어렵군요😦

2022-08-09 15:09 UTC, shkisme commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +  private ErrorMessage compareBallAndNumber(int number, int ball) {
메서드 명 수정했습니다! 코드를 짤 때는 분명해보였는데 다시 읽을 때는 확실히 불분명 해보이군요!
볼때마다 새롭네요..🤔

2022-08-09 15:10 UTC, shkisme commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +      e = new Exception(AMOUNT_OUT_OF_RANGE.getMessage());
InputMismatchException 으로 범위를 줄였습니다!

2022-08-09 15:11 UTC, shkisme commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/Game.java
> +  private void printRankList() {
수정하였습니다 ㅎㅎ

2022-08-09 23:04 UTC, gusah009 reviewed
밤늦게까지 하시느라 고생 많으셨습니다!! 🙇‍♂️🙇‍♂️

2022-08-09 23:04 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/lotto/LottoGenerator.java
> +    lottoGenerator = new LottoGenerator();
매번 새로운 `LottoGenerator()`를 만들 필요가 있을까요?

2022-08-09 23:04 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/Game.java
> +      SaveLotto saveLotto = SaveLotto.saveUserLotto(user, lottoGenerator.generateLotto());
로또의 생성과 user에게 저장하는 로직을 분리한 건 좋은 것 같습니다! 조금 더 제안을 드리자면,

1. [정적 팩터리 메서드 네이밍](https://multifrontgarden.tistory.com/255) `newLottoGenerator()`대신 다른 네이밍을 사용할 수 있을 것 같습니다!
2. 로또를 저장하는 대상은 항상 `user`입니다. 그렇다면 `SaveLotto`라는 새로운 클래스를 만들기보다, `user.saveLotto()`처럼 `user`에게 그 기능을 넘겨주는 건 어떨까요?

2022-08-09 23:04 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> -      set.add(Integer.parseInt(number));
👍👍👍

2022-08-09 23:04 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +  private void isBonusBallAndNumberMatch(int number, int ball) throws Exception {
`is`로 시작하는 메서드는 `boolean`을 반환하길 기대하는데, `void`를 반환해서 당황했습니다. stream을 이용해서 오류를 처리하도록 로직을 바꿨으니 메서드명도 한 번 그에 맞게 바꿔보는 것도 좋을 것 같습니다!

2022-08-09 23:04 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +    List<Integer> winningLottoNumberList = Pattern.compile(",").splitAsStream(winningLottoNumber)
단순히 `.split(',')`후 `stream`으로 변환하지 않고 `Pattern`을 사용하신 이유가 있나요?

2022-08-09 23:04 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +        .collect(Collectors.toList());
조금 더 길이를 줄일 수 있을 것 같습니다!

2022-08-09 23:04 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
>        scanner = new Scanner(System.in);
새로운 Scanner를 할당해주는 이유가 있을까요?

2022-08-09 23:04 UTC, gusah009 commented on shkisme/java_lotto/src/test/java/javalotto/javalotto/error/LottoTicketTest.java
> +  private void setSystemInput(String input) {
`setSystemInput`이 두 번 나오는 것 같습니다. 어떻게 컴파일 에러가 안떴지?

2022-08-09 23:04 UTC, gusah009 commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/lotto/WinningLotto.java
> +  public Rank match(Lotto userLotto) {
👍👍👍 나중에 `Rank`데이터가 삽입, 수정, 삭제가 일어날 수 있다고도 가정하고 만들어보면 더 좋을 것 같습니다!

2022-08-15 02:10 UTC, shkisme commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +  private void isBonusBallAndNumberMatch(int number, int ball) throws Exception {
앗..! 처음에 boolean을 반환하도록 짰다가 void를 반환하도록 수정했는데 메서드 명을 안 바꾸었네요!! 수정했습니다!

2022-08-15 02:22 UTC, shkisme commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
>        scanner = new Scanner(System.in);
입력 버퍼에 있는 잘못된 input을 비워주기 위함입니다!

2022-08-15 03:19 UTC, shkisme commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GameInput.java
> +    List<Integer> winningLottoNumberList = Pattern.compile(",").splitAsStream(winningLottoNumber)
문자열 분할 방법 중에 splitAsStream() 방법을 사용해보고자 이 방법을 사용하였습니다!

2022-08-15 07:56 UTC, JeonghakLee commented on shkisme/java_lotto/src/main/java/javalotto/javalotto/game/GamePrint.java
> +  }
rankList 대신 Rank를 key로 하고 value는 빈도수를 저장하는  식으로 Map 자료형을 사용한다면 복잡도적인 측면에서 조금 더 효율적일 것 같습니다. 또 결과를 출력하는 곳에서 빈도수를 세지 않아도 되는 장점도 생길 것 같은데 혹시 어떻게 생각하시나요??

2022-08-16 10:08 UTC, woo-chang approved these changes
현모님이 너무 열심히 리뷰해주셨네요! 점점 발전하는 모습이 보기 좋아용 수고하셨습니다~

2022-10-16 10:40 UTC, gusah009 approved these changes
지금 하고 계신 자바 스터디에서 또 한 번 코딩해봐도 좋을 것 같습니다!!

수고하셨습니다!! 👏👏

2022-10-16 11:50 UTC, merged